name:                lakka
version:             0.1.0.0
github:              "elpinal/lakka"
license:             MIT
author:              "El Pin Al"
maintainer:          "example@example.com"
copyright:           "2018 El Pin Al"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/elpinal/lakka#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10.2

library:
  source-dirs: src

tests:
  lakka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lakka
    - hspec
